version: '3.8'

services:
  mysql:
    image: mysql
    container_name: api_shop_mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"